name: Build and Deploy Java App Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      MYSQL_HOST_WITH_PORT: ${{ secrets.MYSQL_HOST_WITH_PORT }}
      MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
    outputs:
      ecr-registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.1
      with:
        fetch-depth: 0
                        
    - name: Build and analyze
      run: |
        mvn clean package
        # mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }} 

    # - name: SonarQube Quality Gate Check
    #   id: quality-gate-check
    #   uses: SonarSource/sonarqube-quality-gate-action@v1.1.0
    #   with:
    #     scanMetadataReportFile: target/sonar/report-task.txt
    #   env:
    #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # - name: Add Quality gate status to summary
    #   run: |
    #     echo "Quality gate status = ${{ steps.quality-gate-check.outputs.quality-gate-status }}" >> $GITHUB_STEP_SUMMARY
    #     echo "$(cat target/site/jacoco/index.html)" >> $GITHUB_STEP_SUMMARY
                
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_GHA_ROLE }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    # - name: Set ECR Registry as an output
    #   id: ecr-registry
    #   run: echo "ecr-registry=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_OUTPUT
      
    - name: Build and Tag Docker Image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
      run: |
        IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c 1-7)
        docker build --build-arg MYSQL_HOST_WITH_PORT=$MYSQL_HOST_WITH_PORT --build-arg MYSQL_DB_NAME=$MYSQL_DB_NAME --build-arg MYSQL_USER=$MYSQL_USER --build-arg MYSQL_PASSWORD=$MYSQL_PASSWORD -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO_NAME }}:`$(echo ${GITHUB_SHA} | cut -c 1-7)`'
        format: 'table'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        
    - name: Docker Push to ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
      run: |
        IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c 1-7)
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: SSH into EC2 and deploy Docker container
      env:
        REGISTRY: ${{ needs.build.outputs.ecr-registry }}
        REPOSITORY: ${{ secrets.ECR_REPO_NAME }}
      run: |
        IMAGE_TAG=$(echo ${GITHUB_SHA} | cut -c 1-7)
        # [ ! -d ~/.ssh ] && mkdir -p ~/.ssh && echo "Directory ~/.ssh created." || echo "Directory ~/.ssh already exists."
        echo "${{ secrets.PEM_FILE }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $REGISTRY
        if docker ps -q --filter "name=${{ secrets.CONTAINER_NAME }}" 2>/dev/null ; then
          docker stop "${{ secrets.CONTAINER_NAME }}"
          docker rm "${{ secrets.CONTAINER_NAME }}"
          docker run -d -p "${{ secrets.CONTAINER_PORT_MAPPING }}" --name "${{ secrets.CONTAINER_NAME }}" "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          aws ecr batch-delete-image --region ${{ secrets.AWS_REGION }} --repository-name $REPOSITORY --image-ids imageTag=$IMAGE_TAG
        else
          docker run -d -p "${{ secrets.CONTAINER_PORT_MAPPING }}" --name "${{ secrets.CONTAINER_NAME }}" "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
          aws ecr batch-delete-image --region ${{ secrets.AWS_REGION }} --repository-name $REPOSITORY --image-ids imageTag=$IMAGE_TAG
        fi     
        "

  
      
